import keyMirror from 'fbjs/lib/keyMirror'

export const authActionTypes = keyMirror({
  AUTH_LOGIN_REQUEST: null,
  AUTH_LOGIN_SUCCESS: null,
  AUTH_LOGIN_FAILURE: null,
  AUTH_LOGOUT_REQUEST: null,
  AUTH_LOGOUT_SUCCESS: null,
  AUTH_LOGOUT_FAILURE: null,
  AUTH_GET_USER_REQUEST: null,
  AUTH_GET_USER_SUCCESS: null,
  AUTH_PATCH_USER_REQUEST: null,
  AUTH_PATCH_USER_SUCCESS: null,
  AUTH_RESET_PASSWORD_REQUEST: null,
  AUTH_RESET_PASSWORD_SUCCESS: null,
  AUTH_RESET_PASSWORD_FAILURE: null,
  AUTH_NEW_PASSWORD_REQUEST: null,
  AUTH_NEW_PASSWORD_FAILURE: null,
  AUTH_NEW_PASSWORD_SUCCESS: null,
  AUTH_CREATE_USER_REQUEST: null,
});